agalwood/Motrix

- .electron-vue/webpack.main.config.js
- .travis.yml
- src/main/configs/engine.js
Windows 本地调试报 appId 和 engine 未找到，PR 修复了这些问题。如果需要 Windows 测试，我可以提供帮助。
> fix: appId and engine not found in Windows development

- src/shared/locales/fr/preferences.js
Fix typo into `src/shared/locales/fr/preferences.js`.
> fix: i18n fr in preferences

- src/renderer/components/Preference/Index.vue
- src/renderer/components/Theme/Dark.scss
- src/renderer/components/Theme/Dark/Variables.scss
- src/renderer/components/Theme/Default.scss
- src/renderer/components/Theme/Light/Variables.scss
Currently, the form action buttons overlap the underlying preferences giving poor readability. I have added a background to the `form-actions div` so the UI maintains good readability. I also added the appropriate themeing styles.
This is a quick & dirty fix that _works_ without changing too much of the layout.
> feat: add background under form-actions in preferences

- src/main/core/EnergyManager.js
Energy management stopPowerSaveBlocker does not correctly handle the case where psbId is 0.
Fixes #418
> fix: stopPowerSaveBlocker when psbId = 0

- .electron-vue/webpack.renderer.config.js
- .electron-vue/webpack.web.config.js
```javascript
npm run dev
...
ERROR in Template execution failed: ReferenceError: process is not defined
ERROR in   ReferenceError: process is not defined
- index.ejs:11 eval
[.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
- index.ejs:16 module.exports
[.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
- index.js:284
[Motrix]/[html-webpack-plugin]/index.js:284:18
- runMicrotasks
- task_queues.js:93 processTicksAndRejections
internal/process/task_queues.js:93:5
...
```
https://github.com/SimulatedGREG/electron-vue/issues/871#issuecomment-490370237
Fixes #267
> fix: process is not defined at node 12.x #267

- src/main/Application.js
- src/renderer/components/Native/SelectDirectory.vue
Selecting the folder failed and found that dialog.showOpenDialog is also promisify.
> fix: electron v7 dialog showOpenDialog promisify

- extra/darwin/engine/aria2.conf
- extra/linux/engine/aria2.conf
- extra/win32/engine/aria2.conf
- fix rebuild aria2c
- chore: disable bt-force-encryption
static build script:
https://github.com/aria2/aria2/blob/master/makerelease-osx.mk
Fix #628
> fix: rebuild darwin aria2c v1.35

- README-CN.md
- README.md
- src/main/Application.js
- src/main/ui/TrayManager.js
- src/renderer/components/Logo/Logo.vue
- src/shared/keymap.json
- docs: update readme snapcraft link
- fix: linux tray not support right-click event
https://www.electronjs.org/docs/api/tray#event-right-click-macos-windows
None
> fix: linux tray not support right-click event

- .electron-vue/webpack.renderer.config.js
- .electron-vue/webpack.web.config.js
- fix: webpack copy plugin path
None
> fix: webpack copy plugin path

- src/main/Application.js
- src/main/core/ProtocolManager.js
- src/main/menus/darwin.json
- src/main/menus/linux.json
- src/main/menus/touchBar.json
- src/main/menus/tray.json
- src/main/menus/win32.json
- src/main/utils/menu.js
- src/renderer/components/Preference/Advanced.vue
- src/renderer/components/Preference/Basic.vue
- src/renderer/components/Task/AddTask.vue
- src/renderer/components/Task/Index.vue
- src/renderer/pages/index/commands.js
- src/renderer/utils/native.js
- src/renderer/utils/task.js
- src/shared/utils/tracker.js
Support motrix:// to call Motrix, create new tasks, open preferences, etc.
```
// New Task
motrix://new-task?uri=URL&out=NAME&dir=DIR
// Add Task silently, no confirmation
motrix://new-task?uri=URL&out=NAME&silent=true
// Open Preference
motrix://preferences
// Open About
motrix://about
```
> refactor: redesign motrix scheme

- src/renderer/components/Native/EngineClient.vue
- src/renderer/components/Task/Index.vue
- src/renderer/components/Task/TaskItem.vue
- src/renderer/components/Task/TaskItemActions.vue
- src/renderer/store/modules/task.js
- src/renderer/utils/native.js
- src/shared/locales/bg/task.js
- src/shared/locales/ca/task.js
- src/shared/locales/de/task.js
- src/shared/locales/en-US/task.js
- src/shared/locales/es/task.js
- src/shared/locales/fa/task.js
- src/shared/locales/fr/task.js
- src/shared/locales/id/task.js
- src/shared/locales/ja/task.js
- src/shared/locales/ko/task.js
- src/shared/locales/pt-BR/task.js
- src/shared/locales/ru/task.js
- src/shared/locales/tr/task.js
- src/shared/locales/uk/task.js
- src/shared/locales/vi/task.js
- src/shared/locales/zh-CN/task.js
- src/shared/locales/zh-TW/task.js
- src/shared/utils/index.js
The aria2 BT task stops seeding by calling [changeOption](https://aria2.github.io/manual/en/html/aria2c.html#aria2.changeOption) to modify the `seed-time` of the task. 
After calling changeOption, aria2 will suspend the task and restart the task, so the corresponding notification will be triggered.
Refactored the logic of task notification to reduce the interference to users.
Closed #604
> fix: stop bt task seeding notification #604

- src/shared/constants.js
突然发现 Motrix 把我的 [XIU2/TrackersListCollection](https://github.com/XIU2/TrackersListCollection) 项目加到 Tracker 推荐列表里了 😲 点个赞！  
不过我突然发现怎么有个 `other.txt` 😅...  
这个文件只是我偶尔把一些单独的 Tracker 地址放进去以集成到最终成品列表中（`all.txt、best.txt、http.txt`）。  
正好 7 月的时候，添加了一个仅 HTTP(S) 列表：`http.txt` ，可以用来更换 other.txt ！  
****
发了个 [Issues](https://github.com/agalwood/Motrix/issues/782) 后发现没人吭声，好尴尬，于是我就自己修改并请求合并了~  
只是将 `src/shared/constants.js` 文件内的 `other.txt` 更换为 `http.txt` 。
#782
> fix: replace TrackersListCollection other.txt with http.txt

- README-CN.md
- README.md
Fix error when installing using latest Homebrew in macOS. Just fix README.md.
screenshot:
> docs: Fix installation instructions in README.md

- src/main/ui/TrayManager.js
- src/renderer/components/Native/DynamicTray.vue
- src/renderer/store/modules/app.js
- src/renderer/utils/native.js
- src/shared/utils/index.js
Use template image as tray icon when runs on macOS big sur.
The color is handled by system, so the active status green dot is not able to show.
However, according to [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/), we shall use template image to represent a uniform appearance style.
Fixes #804
Fixes #820
> fix: big sur tray color

- src/renderer/components/Native/DynamicTray.vue
The tray has a retina-related bug. When the Macbook Pro is connected to a non-retina display and the application window runs on a non-retina display, the size of the tray icon with speed will be abnormal.
Fix #841
> refactor: dynamic tray scale

- src/main/Application.js
- src/main/core/UpdateManager.js
- src/main/ui/ThemeManager.js
- src/renderer/components/Theme/Default.scss
- src/renderer/components/Theme/Variables.scss
- src/renderer/store/modules/task.js
- src/shared/utils/rename.js
- fix: auto update exception
- fix: auto theme #937
- fix: add one task triggered rename rule #845
- fix: task detail not auto hide when remove task
- fix: element ui message z-index
Closed #845
> fix: some bug

- package.json
- src/main/ui/WindowManager.js
- src/renderer/components/Aside/Index.vue
- src/renderer/pages/index/main.js
Add vibrancy sidebar for macOS
> feat: add vibrancy sidebar for macos

- src/main/core/ConfigManager.js
- src/renderer/components/Preference/Basic.vue
- src/renderer/components/TaskDetail/Index.vue
- src/renderer/utils/task.js
- src/shared/locales/zh-CN/preferences.js
Tasks list in task detail has wrong items when user switch between different task. I remove old items which shouldn't appear in new list.
Add a switch for auto download magnet link and torrent. Users can choose whether to automatically start downloading all the files in the torrent or whether to download only the torrent file itself.
Fixes #971
Close #934
Close #440
> fix: tasks list has old wrong items and add switch for auto download torrent

- src/main/ui/TrayManager.js
- src/main/ui/WindowManager.js
- src/renderer/components/Native/DynamicTray.vue
- src/renderer/store/modules/app.js
- src/renderer/utils/native.js
- src/shared/utils/index.js
Always use template icon.
Fixes dark menu tray icon for macOS 10.13 High Sierra and before.
Fixes #1008
Related to #951
> fix: macos dark menu

- src/main/ui/TrayManager.js
macOS should not have tray icon tooltip.
Also, it‘s wierd sometimes.
> fix: do not show tray tooltip for macOS

- build/afterSignHook.js
- electron-builder.json
- extra/darwin/arm64/engine/aria2.conf
- extra/darwin/x64/engine/aria2.conf
- extra/linux/engine/aria2.conf
- extra/win32/ia32/engine/aria2.conf
- extra/win32/x64/engine/aria2.conf
- package.json
- src/main/Application.js
- src/main/core/ConfigManager.js
- src/main/core/UPnPManager.js
- src/main/ui/DockManager.js
- src/shared/constants.js
- src/shared/locales/en-US/task.js
- src/shared/ua.js
- yarn.lock
- chore: update Transmission mock version
- refactor: dock manager
- chore: change jsdelivr cdn url
- refactor: simplified upnp mapping fail log
- chore: change notarize deps
- chore: bump @motrix/nat-api version
- chore: i18n update stop seeding tip
> fix: some fix

- src/renderer/components/Task/AddTask.vue
Prevent from accidental close.
None
> feat: lock AddTask dialog

- .github/ISSUE_TEMPLATE/1_bug_report.yml
Close #1421 
I made only the English bug report template to find out is it effective or not to use the new issue template with yml.
> chore: Create New Bug Report Issue Template to prevent bad contributor experience

- package.json
- src/main/configs/page.js
- src/main/ui/MenuManager.js
- src/main/ui/WindowManager.js
- src/main/utils/index.js
- src/renderer/components/Preference/Basic.vue
- src/shared/utils/index.js
- yarn.lock
- fix: BrowserWindow rendering bug under linux
- chore: declare node version >= 18
- fix: preference basic need confirm but not changed
> fix: BrowserWindow rendering bug under linux

- src/shared/utils/index.js
When cookie/referer are set at the same time, aria2 failed to parse the cookie/referer arguments, and the target cannot be downloaded.
If only cookie is set, aria2 can successfully download the target.
Because 
```javascript
result[kebabCaseKey] = `${options[key]}`
```
joins the array element with ','
Adapt it to 
```javascript
result[kebabCaseKey] = options[key].join('\n')
```
works on my side
> fix: bug regarding cookie/referer

- README-CN.md
- README.md
- package.json
- src/renderer/utils/task.js
- src/shared/utils/curl.js
- src/shared/utils/index.js
- yarn.lock
For more convenient to use with DevTools, I add cURL support that can automatically parse informations from cURL commands.
We can use `Copy as cURL` with DevTools and paste it in motrix to download with cookie/referer/user-agent informations.
This is convenient to download from websites that require cookie/referer, e.g. Google Drive
> feat: Add cURL support for convenient download with cookie/referer information

- src/renderer/components/Preference/Advanced.vue
- src/renderer/components/Preference/Basic.vue
fix: btAutoDownloadContent boolean is inverted
Close #1471
> fix: btAutoDownloadContent boolean is inverted
