- src/renderer/components/Main.vue
- src/renderer/components/Task/SelectTorrent.vue
- src/renderer/store/modules/app.js
document.ondragover  document.ondrop 几个事件监听好像应该换个位置？
> feat: add drag file

- src/renderer/components/Task/AddTask.vue
> fix: Form Labels in add Task

- src/renderer/components/Native/EngineClient.vue
- src/renderer/components/Task/AddTask.vue
- src/renderer/components/Task/TaskActions.vue
- src/renderer/components/Task/TaskItem.vue
- src/renderer/components/Task/TaskItemActions.vue
- src/renderer/components/Task/TaskItemInfo.vue
- src/renderer/components/Task/TaskList.vue
- src/renderer/components/Theme/Base.scss
- src/shared/utils.js
Added showClose: true to all $message calls in addition to [hotfix/fix_task_name_overflow_201902151144](https://github.com/agalwood/Motrix/tree/hotfix/fix_task_name_overflow_201902151144)
> feat: Make notifications dismissible and truncate long messages 

- .editorconfig
- package-lock.json
- src/renderer/components/Msg/index.js
- src/renderer/components/Native/EngineClient.vue
- src/renderer/components/Task/AddTask.vue
- src/renderer/components/Task/TaskActions.vue
- src/renderer/components/Task/TaskItem.vue
- src/renderer/components/Task/TaskItemActions.vue
- src/renderer/pages/index/main.js
refactor: rename message to msg
feat: msg can set default options
feat: msg only play last 5 messages in a moment
#66
> refactor: message refactor

- README.md
Some stylistic revisions, a few grammar edits, and some typos fixed.
> fix: README.md editing

- README.md
> docs: readme added linux installation guide

- package-lock.json
- src/renderer/components/Aside/Index.vue
- src/renderer/components/Theme/Default.scss
The current version can also be dragged and dropped on the buttons in the aside panel, sometimes affecting the operation.
https://s2.svend.cc/temp/motrix-1.gif
now!
https://s2.svend.cc/temp/motrix-2.gif
> fix: remove the button in the aside panel to drag and drop

- src/renderer/components/Preference/Advanced.vue
- src/renderer/components/Preference/Basic.vue
- src/shared/configKeys.js
- src/shared/utils.js
The hideAppMenu option currently needs to restart the app.
> fix: check changed preferences is need restart

- src/renderer/api/Api.js
- src/renderer/components/Task/AddTask.vue
- src/renderer/store/modules/task.js
- src/shared/rename.js
Out rule sample:
abc_(001+).jpg
xyz_(100-2).html
> feat: add task out support rule #326

- src/renderer/components/Task/TaskItemActions.vue
Hold the shift key and click the delete task button will automatically check 'Delete with Files'.
Related to #317
> feat: shift delete task with files

- src/renderer/components/Preference/Advanced.vue
- src/renderer/components/Preference/Basic.vue
- src/renderer/components/Preference/Lab.vue
The changed data outdated after the preferences are saved. The result of the next diff may not be correct.
None
> fix: preferences changed data outdated

- src/shared/locales/uk/task.js
> fix: Fixed spelling issue.

- extra/README.md
fix https://github.com/agalwood/Motrix/issues/381
~* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?~
~* [x] Have you linted your code locally prior to submission?~
~* [x] Have you successfully ran app with your changes locally?~
> docs: Create extra/README.md

- src/main/Launcher.js
- src/main/core/ConfigManager.js
- src/renderer/api/Api.js
- src/renderer/store/modules/preference.js
- src/shared/constants.js
User config allows custom tracker sources.
Fixes #416
> feat: custom tracker source

- src/shared/locales/es/about.js
Typo fixed on line 02
There is no related previous issue or PR
> fix: Typo fixed on line 02

- src/main/configs/page.js
- src/renderer/components/Aside/Index.vue
- src/renderer/components/Icons/menu-add.js
- src/renderer/components/Task/AddTask.vue
- src/renderer/components/Task/Index.vue
- src/renderer/components/Task/TaskActions.vue
- src/renderer/components/Task/TaskSwitcher.vue
- src/renderer/components/Theme/Default.scss
For now, Motrix restricts electron Window bounds-width to 840px which is good enough for most use cases. However as a download manager there's a number of ways that it's window size  might be too large.Many people have such a demand. So with the help of  element-ui we can support smaller window size without making breaking changes. And continuous improvements will be made in no time.
> feat: make Motrix layout more responsive for supporting Mini mode

- src/renderer/components/Preference/Advanced.vue
- src/shared/locales/ca/preferences.js
- src/shared/locales/de/preferences.js
- src/shared/locales/es/preferences.js
- src/shared/locales/fa/preferences.js
- src/shared/locales/fr/preferences.js
- src/shared/locales/ja/preferences.js
- src/shared/locales/ko/preferences.js
- src/shared/locales/pt-BR/preferences.js
- src/shared/locales/ru/preferences.js
- src/shared/locales/tr/preferences.js
- src/shared/locales/uk/preferences.js
- src/shared/locales/zh-CN/preferences.js
- src/shared/locales/zh-TW/preferences.js
Perference advanced panel add proxy tip, [View Proxy Manual](https://github.com/agalwood/Motrix/wiki/Proxy)
Related to #320 , #488
> feat: Perference advanced panel add proxy tip

- src/main/ui/TouchBarManager.js
Adapt the new api of Electron's TouchBar
<https://www.electronjs.org/docs/api/touch-bar>
None
> fix: adapt the new api of Electron's TouchBar

- src/renderer/components/Native/TitleBar.vue
- src/renderer/components/Theme/Dark/Variables.scss
- src/renderer/components/Theme/Light/Variables.scss
- Remove the title bar button spacing
- Adjust the close button color for win & linux
#461
> feat: improve win & linux title bar style

- src/main/Application.js
- src/main/core/ConfigManager.js
- src/main/ui/WindowManager.js
- src/renderer/components/Preference/Basic.vue
- src/shared/configKeys.js
- src/shared/locales/ca/preferences.js
- src/shared/locales/de/preferences.js
- src/shared/locales/en-US/preferences.js
- src/shared/locales/es/preferences.js
- src/shared/locales/fa/preferences.js
- src/shared/locales/fr/preferences.js
- src/shared/locales/ja/preferences.js
- src/shared/locales/ko/preferences.js
- src/shared/locales/pt-BR/preferences.js
- src/shared/locales/ru/preferences.js
- src/shared/locales/tr/preferences.js
- src/shared/locales/uk/preferences.js
- src/shared/locales/zh-CN/preferences.js
- src/shared/locales/zh-TW/preferences.js
Automatically hide window when losing focus
> feat: Automatically hide window when losing focus

- .travis.yml
- appveyor.yml
> chore: update ci conf

- src/main/core/ConfigManager.js
- src/main/core/ProtocolManager.js
- src/main/ui/ThemeManager.js
- src/main/ui/TrayManager.js
- src/renderer/components/Aside/Index.vue
- src/renderer/components/Command/index.js
- src/renderer/components/Dragger/Index.vue
- src/renderer/components/Native/ShowInFolder.vue
- src/renderer/components/Native/utils.js
- src/renderer/components/Preference/Basic.vue
- src/renderer/components/Preference/ThemeSwitcher.vue
- src/renderer/components/Task/AddTask.vue
- src/renderer/components/Task/TaskActions.vue
- src/renderer/components/Task/TaskItemActions.vue
- src/renderer/pages/index/App.vue
- src/renderer/store/modules/app.js
- src/shared/constants.js
- fixed: show task item in folder issue
- fixed: move task item to trash issue
- fixed: disabled dir prettify
- refactor: some constants
Related to #575
> fix: several file path related issues

- .eslintrc.js
- .github/workflows/release.yml
- .travis.yml
- build/afterPackHook.js
- build/afterSignHook.js
- package-lock.json
- package.json
- feat: try github action to build
None
> feat: github action

- extra/darwin/engine/aria2.conf
- extra/linux/engine/aria2.conf
- extra/win32/engine/aria2.conf
Compile it with reference to the script of q3aql/aria2-static-builds. The difference from the official version of Aria2 is that the max-connection-per-server is modified to 64.
https://github.com/q3aql/aria2-static-builds
Related to #558 #589 #433 #404 #325 #263 #36
> feat: upgrade aria2 to v1.35.0

- .travis.yml
- appveyor.yml
- package.json
- src/main/Application.js
- src/main/core/ConfigManager.js
- src/main/core/Engine.js
- src/main/core/UPnPManager.js
- src/main/ui/WindowManager.js
- src/main/utils/index.js
- src/renderer/api/Api.js
- src/renderer/components/About/AboutPanel.vue
- src/renderer/components/About/Copyright.vue
- src/renderer/components/Browser/index.vue
- src/renderer/components/Command/index.js
- src/renderer/components/DragSelect/Index.vue
- src/renderer/components/Native/utils.js
- src/renderer/components/Preference/Basic.vue
- src/renderer/components/Preference/Lab.vue
- src/renderer/components/Task/TaskItemActions.vue
- src/renderer/store/modules/task.js
- src/shared/constants.js
- src/shared/locales/zh-CN/task.js
- src/shared/locales/zh-TW/task.js
- refacotr: improve upnp port unmapping speed
- refactor: redesigned the lab page
- feat: implemented menu pause & resume task
- fix: app menu title typo
> refactor: redesigned the lab page

- package-lock.json
- package.json
- src/renderer/components/Native/EngineClient.vue
- src/renderer/components/Task/TaskActions.vue
- fix: save session delay too long
- fix: hide delete selected tasks on stopped task list
None
> fix: improve task manage

- src/main/Application.js
- src/main/core/AutoLaunchManager.js
- src/main/core/ConfigManager.js
- src/main/core/UPnPManager.js
- src/main/ui/MenuManager.js
- src/main/ui/ThemeManager.js
- src/main/ui/WindowManager.js
- src/main/utils/index.js
- src/renderer/components/Native/EngineClient.vue
- src/renderer/components/Native/TitleBar.vue
- src/renderer/utils/native.js
- src/shared/constants.js
- fix: upnp client is destroyed #662
- fix: full screen mode no traffic light #663
- refactor: improve macOS fullscreen mode usability
- refactor: remove title bar buttons spacer
Close #662 
Close #663
> fix: upnp client & full screen issues

- src/main/Application.js
- src/main/ui/DockManager.js
- src/main/ui/WindowManager.js
- src/renderer/components/Preference/Basic.vue
- fix: full screen save preference issue #663
Closed #663
> fix: full screen save preference issue #663

- jsconfig.json
- src/main/Application.js
- src/main/core/Engine.js
- src/main/core/UpdateManager.js
- src/main/ui/MenuManager.js
- src/renderer/components/Preference/Basic.vue
- fix: show run mode only in macOS
- refactor: add jsconfig
#641
> fix: preference show run mode only in macOS

- src/renderer/components/Preference/Index.vue
- src/renderer/components/Task/TaskProgressInfo.vue
fix: task progress info text font style normal
refactor: form actions position sticky
> fix: some style improve

- src/main/Application.js
- src/main/core/ConfigManager.js
- src/renderer/components/Preference/Advanced.vue
- src/shared/constants.js
- src/shared/utils/tracker.js
Solve the problem that users in mainland China often cannot synchronize tracker.
#729
> feat: add tracker cdn source

- package.json
- src/main/Application.js
- src/main/core/Engine.js
- src/renderer/components/About/Copyright.vue
- src/renderer/components/Task/TaskItem.vue
- src/renderer/components/Task/TaskProgressInfo.vue
- src/renderer/components/TaskDetail/TaskActivity.vue
- src/renderer/components/TaskDetail/TaskPeers.vue
- src/renderer/components/Theme/Default.scss
- yarn.lock
Try to fix app hang caused by nodejs child_process
- fix: app reset engine not start
- fix: app hang caused by child_process spawn
#924
> fix: app hang 

- src/renderer/components/Icons/Icon.vue
- src/renderer/components/Preference/Lab.vue
- src/renderer/components/TaskDetail/Index.vue
- src/renderer/components/TaskDetail/TaskGeneral.vue
- feat: lab page dark theme
- fix: drawer header close icon could not click
- refactor: mo icon
> feat: preference lab panel dark theme

- src/renderer/components/Native/TitleBar.vue
fix Windows titlebar resize issue
#954
> fix: window resize

- src/main/ui/WindowManager.js
A window is visable though it's minimized.
Fixes #1011
> fix: showWindow won't restore minimized window

- package.json
> fix: upgrade webpack cli parameters

- src/main/Application.js
- src/renderer/api/Api.js
- src/renderer/components/Native/EngineClient.vue
- src/renderer/store/modules/app.js
Add a download progress indicator to the taskbar.
Details:
- Show total progress of multiple tasks, excluding tasks of unknown size
- Task of unknown size will show an indeterminate progress bar on Windows, or zero progress on other platforms
- Lower priority than update progress
Resolves #633, resolves #918, resolves #1249
> feat: add taskbar progress

- .github/workflows/release.yml
Use forked  electron-builder-action, upgrade Nodejs to version 16
https://github.com/marketplace/actions/motrix-electron-builder-action
- chore: upgrade snapcraft action
- chore: upgrade electron builder action
> chore: upgrade electron builder action

- app-update.yml
- electron-builder.json
- src/main/Application.js
- src/main/core/UpdateManager.js
- fix: change version 1.8.x auto update url to 'https://dl.motrix.app/releases/'
- fix: handle auto updater update canceled event
> fix: app auto update failed

- README-CN.md
- README.md
> docs: fix yay install script
